{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.name }}-svc
spec:
{{- if .Values.ui.service.externalEnabled }}
  {{- if eq .Values.ui.service.type "NodePort" }}
  type: NodePort
  {{- end }}
  {{- if eq .Values.ui.service.type "LoadBalancer" }}
  type: LoadBalancer
  {{- end }}
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
  - name: {{ .Values.ui.name }}-port
    port: {{ .Values.ui.port | default 8080 }}
    protocol: TCP
    targetPort: {{ .Values.ui.name }}-port
{{- if .Values.ui.service.externalEnabled }}
  {{- if eq .Values.ui.service.type "NodePort" }}
    {{- if .Values.ui.service.nodePort }}
    nodePort: {{ .Values.ui.service.nodePort }}
    {{- end }}
  {{- end }}
{{- end }}
  selector:
    app: {{ .Values.ui.name }}-pod
---
{{- end }}
