{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.name }}-cm
data:
  #1    
  DATAHUB_URL: {{ .Values.env.dataHubUrl | quote }}
  APM_URL: {{ .Values.env.apmUrl | quote }}
  DASHBOARD_URL: {{ .Values.env.dashboardUrl | quote }}
  MOBILE_URL: {{ .Values.env.mobileUrl | quote }}
  NOTIFICATION_URL: {{ .Values.env.notificationUrl | quote }}
  #2
  ADMIN_USERNAME : {{ .Values.env.adminUsername | quote }}
  ADMIN_PASSWORD : {{ .Values.env.adminPassword | quote }}
  DCCS_URL: {{ .Values.env.dccsUrl | quote }}
  SSO_URL : {{ .Values.env.ssoUrl | quote }}
  #3
  API_URL: {{ .Values.env.apiUrl | quote }}
  API_MONGO_URL: {{ .Values.env.apimongoUrl | quote }}
  API_MEASURE_URL: {{ .Values.env.apimeasureUrl | quote }}
  API_MEASURE_MACHINE_URL: {{ .Values.env.apimeasuremachineUrl | quote }}
  API_PLUGIN_URL: {{ .Values.env.apipluginUrl | quote }}
  API_SDK_URL: {{ .Values.env.apisdkUrl | quote }}
  API_SSO_URL: {{ .Values.env.apissoUrl | quote }}
  UI_URL: {{ .Values.env.uiUrl | quote }}
  #4
  MONGODB_URL: {{ .Values.env.mongodbUrl | quote }}
  MONGODB_DATABASE : {{ .Values.env.mongodbDatabase | quote }}
  MONGODB_USERNAME : {{ .Values.env.mongodbUsername | quote }}
  MONGODB_PASSWORD : {{ .Values.env.mongodbPassword | quote }}
  #5
  WISE_URL: {{ .Values.env.wiseUrl | quote }}
  
---
{{- end }}
